name: Update Trading GIF

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        pip install yfinance pillow imageio

    - name: Run Trading Card GIF Generator
      run: python update_trading_card_gif.py

    - name: Commit and Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "actions@github.com"
        git add assets/trading.gif
        git commit -m "🎞️ Update animated trading.gif" || echo "No changes to commit"
        git push
